version: '3.4'
services:

  # https://github.com/home-assistant/home-assistant
  homeassistant:
    build: ./homeassistant/
    restart: unless-stopped
    container_name: homeassistant
    hostname: homeassistant
    ports:
      - 8123:8123/tcp
    environment:
      TZ: "America/Denver"
    volumes:
      - ${HOMEASSISTANT_PATH}:/config:rw
    devices:
      # usb Nortek device forwarded to the docker image
      # zwave
      - /dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_C1300092-if00-port0:/dev/ttyUSB0
      # zigbee
      - /dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_C1300092-if01-port0:/dev/ttyUSB1


  # https://zwave-js.github.io/zwavejs2mqtt/#/README
  # https://hub.docker.com/r/zwavejs/zwavejs2mqtt
  # https://github.com/zwave-js/zwavejs2mqtt/blob/master/docker/docker-compose.yml
  zwavejs2mqtt:
    image: zwavejs/zwavejs2mqtt
    restart: unless-stopped
    container_name: zwavejs2mqtt
    hostname: zwavejs2mqtt
    environment:
      TZ: "America/Denver"
    ports:
      - 8091:8091/tcp # port for web interface
      - 3000:3000/tcp # port for zwave-js websocket server
    volumes:
      - ${ZWAVE_PATH}:/usr/src/app/store
    depends_on:
      - homeassistant
    devices:
      # usb Nortek device forwarded to the docker image
      - /dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_C1300092-if00-port0:/dev/ttyUSB0

  # mqtt broker
  # https://hub.docker.com/_/eclipse-mosquitto
  mosquitto:
    build: ./mosquitto/
    restart: unless-stopped
    container_name: mosquitto
    hostname: mosquitto
    environment:
      TZ: "America/Denver"
    ports:
      - 1883:1883/tcp # standard port
      # this shouldn't be needed
      #- 9001:9001/tcp # websockets
    depends_on:
      - homeassistant
