version: '3.4'
services:

  # https://github.com/dlandon/zoneminder
  zoneminder:
    build: ./zoneminder/
    restart: always
    container_name: zoneminder
    hostname: zoneminder
    privileged: "true"
    ports:
      - 9443:443/tcp
      # this shouldn't need to be exposed outside the Docker compose network
      #- 9000:9000/tcp
    environment:
      TZ: "America/Denver"
      INSTALL_HOOK: "0"
      INSTALL_FACE: "0"
      INSTALL_TINY_YOLO: "0"
      INSTALL_YOLO: "0"
    volumes:
      - ${ZONEMINDER_PATH}/config/:/config:rw
      - zoneminder_data:/var/cache/zoneminder:rw
    # https://docs.docker.com/compose/compose-file/#healthcheck
    healthcheck:
      test: ["CMD", "curl", "-f", "https://192.168.1.226:9443/zm/api/host/getVersion.json"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  # https://github.com/home-assistant/home-assistant
  homeassistant:
    build: ./homeassistant/
    restart: always
    container_name: homeassistant
    hostname: homeassistant
    ports:
      - 8123:8123/tcp
    environment:
      TZ: "America/Denver"
    volumes:
      - ${HOMEASSISTANT_PATH}:/config:rw
      - zoneminder_data:/config/www/zoneminder:ro
    depends_on:
      - zoneminder

  yolo:
    build: ./yolo/
    restart: always
    container_name: yolo
    hostname: yolo
    environment:
      TZ: "America/Denver"
    volumes:
      - zoneminder_data:/var/cache/zoneminder:rw
    depends_on:
      - zoneminder

  # mqtt broker
  # https://hub.docker.com/_/eclipse-mosquitto
  mosquitto:
    build: ./mosquitto/
    restart: always
    container_name: mosquitto
    hostname: mosquitto
    environment:
      TZ: "America/Denver"
    ports:
      - 1883:1883/tcp # standard port
      # this shouldn't be needed
      #- 9001:9001/tcp # websockets
    depends_on:
      - homeassistant

  # a simple flask app to show camera events
  # flaskcamera:
  #   build: ./flaskcamera/
  #   restart: always
  #   container_name: flaskcamera
  #   hostname: flaskcamera
  #   environment:
  #     TZ: "America/Denver"
  #   ports:
  #     - 5001:5000/tcp
  #   volumes:
  #     - zoneminder_data:/config/www/zoneminder:ro
  #   depends_on:
  #     - homeassistant
  #     - zoneminder
  #   # https://docs.docker.com/compose/compose-file/#healthcheck
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:5000/"]
  #     interval: 30s
  #     timeout: 5s
  #     retries: 3
  #     start_period: 10s


# http://blog.code4hire.com/2018/06/define-named-volume-with-host-mount-in-the-docker-compose-file/
# https://docs.docker.com/compose/compose-file/#volume-configuration-reference
volumes:
  zoneminder_data:
    driver: local
    driver_opts:
      type: none
      device: ${ZONEMINDER_PATH}/data/
      o: bind