version: '3.4'
services:

  # https://hub.docker.com/r/zoneminderhq/zoneminder
  zoneminder:
    build: ./zoneminder/
    restart: unless-stopped
    container_name: zoneminder
    hostname: zoneminder
    privileged: "true"
    shm_size: 512m
    ports:
      - 9443:443/tcp
    environment:
      TZ: "America/Denver"
      ZM_DB_USER: 'zoneminder'
      ZM_DB_PASS: 'zoneminder'
      ZM_DB_NAME: 'zm'
      ZM_DB_HOST: 'mariadb'
    depends_on:
      - mariadb
    volumes:
      - zoneminder_events:/var/cache/zoneminder/events:rw
      - zoneminder_images:/var/cache/zoneminder/images:rw
      - zoneminder_logs:/var/log/zoneminder:rw
    # https://docs.docker.com/compose/compose-file/#healthcheck
    healthcheck:
      test: ["CMD", "curl", "-f", "https://192.168.1.226:9443/zm/api/host/getVersion.json"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  # https://hub.docker.com/_/mariadb
  mariadb:
    build: ./mariadb/
    restart: unless-stopped
    container_name: mariadb
    hostname: mariadb
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - zoneminder_mysql:/var/lib/mysql:rw


  # https://github.com/home-assistant/home-assistant
  homeassistant:
    build: ./homeassistant/
    restart: unless-stopped
    container_name: homeassistant
    hostname: homeassistant
    ports:
      - 8123:8123/tcp
    environment:
      TZ: "America/Denver"
    volumes:
      - ${HOMEASSISTANT_PATH}:/config:rw
      - zoneminder_data:/config/www/zoneminder:ro
    depends_on:
      - zoneminder
    devices:
      # usb Nortek device forwarded to the docker image
      # zwave
      - /dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_C1300092-if00-port0:/dev/ttyUSB0
      # zigbee
      - /dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_C1300092-if01-port0:/dev/ttyUSB1


  # https://zwave-js.github.io/zwavejs2mqtt/#/README
  # https://hub.docker.com/r/zwavejs/zwavejs2mqtt
  # https://github.com/zwave-js/zwavejs2mqtt/blob/master/docker/docker-compose.yml
  zwavejs2mqtt:
    image: zwavejs/zwavejs2mqtt
    restart: unless-stopped
    container_name: zwavejs2mqtt
    hostname: zwavejs2mqtt
    environment:
      TZ: "America/Denver"
    ports:
      - 8091:8091/tcp # port for web interface
      - 3000:3000/tcp # port for zwave-js websocket server
    volumes:
      - ${ZWAVE_PATH}:/usr/src/app/store
    depends_on:
      - homeassistant
    devices:
      # usb Nortek device forwarded to the docker image
      - /dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_C1300092-if00-port0:/dev/ttyUSB0

  # mqtt broker
  # https://hub.docker.com/_/eclipse-mosquitto
  mosquitto:
    build: ./mosquitto/
    restart: unless-stopped
    container_name: mosquitto
    hostname: mosquitto
    environment:
      TZ: "America/Denver"
    ports:
      - 1883:1883/tcp # standard port
      # this shouldn't be needed
      #- 9001:9001/tcp # websockets
    depends_on:
      - homeassistant

# http://blog.code4hire.com/2018/06/define-named-volume-with-host-mount-in-the-docker-compose-file/
# https://docs.docker.com/compose/compose-file/#volume-configuration-reference
volumes:
  zoneminder_data:
    driver: local
    driver_opts:
      type: none
      device: ${ZONEMINDER_PATH}/data/
      o: bind
  zoneminder_events:
    driver: local
    driver_opts:
      type: none
      device: ${ZONEMINDER_PATH}/data/events/
      o: bind
  zoneminder_images:
    driver: local
    driver_opts:
      type: none
      device: ${ZONEMINDER_PATH}/data/images/
      o: bind
  zoneminder_mysql:
    driver: local
    driver_opts:
      type: none
      device: ${ZONEMINDER_PATH}/data/mysql/
      o: bind
  zoneminder_logs:
    driver: local
    driver_opts:
      type: none
      device: ${ZONEMINDER_PATH}/data/logs/
      o: bind