
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: 192.168.1.123:8123
  # turn off self-signed certs because the Android app can't deal with them
  #ssl_certificate: /config/ssl/cert.crt
  #ssl_key: /config/ssl/cert.key

# https://www.home-assistant.io/integrations/zoneminder/
zoneminder:
  host: 192.168.1.113:8443
  path: /zm/
  ssl: True
  verify_ssl: False

# https://www.home-assistant.io/integrations/zoneminder/#switch
switch:
  - platform: zoneminder
    command_on: Mocord
    command_off: None

camera:
  platform: zoneminder

# https://www.home-assistant.io/integrations/nws/
weather:
  platform: nws
  api_key: firefly2442@gmail.com
  station: KABQ # ABQ airport https://www.wrh.noaa.gov/cnrfc/rsa_getObs.php?sid=ABQ&num=24

sensor:
  # https://www.home-assistant.io/integrations/systemmonitor/
  # TODO: how can we define multiple disks/mounts here?
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: memory_use_percent
      - type: swap_use_percent
      - type: load_5m
  # https://www.home-assistant.io/integrations/version/
  - platform: version
  # https://www.home-assistant.io/integrations/zoneminder/
  - platform: zoneminder
    include_archived: False
  # https://www.home-assistant.io/integrations/uptime/
  - platform: uptime
    name: Uptime
    unit_of_measurement: days
  # https://www.home-assistant.io/integrations/sensor.command_line/#cpu-temperature
  - platform: command_line
    name: CPU Temperature
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    # If errors occur, make sure configuration file is encoded as UTF-8
    unit_of_measurement: "°F"
    # make sure to set the corresponding unit system in configuration -> general, this seems to override the unit of measurement
    value_template: '{{ (value | multiply(0.001) * 1.8 + 32) | round(1) }}'
  # https://www.home-assistant.io/integrations/rest
  - platform: rest
    # https://www.home-assistant.io/docs/configuration/platform_options/
    scan_interval: 600 # run every 10 minutes, default on local polling of sensors is 30 seconds
    resource: https://192.168.1.113:8443/zm/api/host/getVersion.json
    name: zoneminder_version
    verify_ssl: false
    json_attributes:
      - version

# https://www.home-assistant.io/lovelace/yaml-mode/
lovelace:
  mode: yaml

device_tracker:
  # https://www.home-assistant.io/integrations/luci/
  - platform: luci
    host: 192.168.1.1
    username: root
    # https://www.home-assistant.io/docs/configuration/secrets/
    password: !secret openwrt_password
    ssl: True
    verify_ssl: False

# https://community.home-assistant.io/t/picture-for-person-component-and-zone-naming-enhancement-for-home-and-not-home/103835/7
homeassistant:
  customize:
    person.patrick:
      entity_picture: /local/binary_logo.jpg

# https://www.home-assistant.io/docs/automation/
automation:
  - alias: 'Turn on camera when away'
    trigger:
      platform: state
      entity_id: person.patrick
      to: not_home
    action:
      service: switch.turn_on
      entity_id: switch.sidecamera_state
  - alias: 'Turn off camera when home'
    trigger:
      platform: state
      entity_id: person.patrick
      to: home
    action:
      service: switch.turn_off
      entity_id: switch.sidecamera_state
