title: Home
views:
  - title: Controls
    cards:
      # https://www.home-assistant.io/lovelace/entities/
      - type: entities
        title: Lights
        show_header_toggle: false
        entities:
          - entity: switch.office_lamp
            icon: mdi:lamp
          - entity: switch.living_room_lamp
            icon: mdi:floor-lamp
          - entity: switch.nodeid_4_switch
            name: Outside Lights
            icon: mdi:outdoor-lamp
          
      # https://www.home-assistant.io/lovelace/entities/
      - type: entities
        title: Arm Alarm
        show_header_toggle: false
        entities:
          - entity: switch.garage_switch
            name: Away
            icon: mdi:light-switch
          - type: divider
          - entity: input_boolean.alarm_away
            name: Home
            icon: mdi:light-switch
      - type: entities
        title: Intruder! Alarm!
        show_header_toggle: false
        entities:
          - entity: input_boolean.alarm
            name: Intruder! Alarm!
            icon: mdi:alarm-light
      - type: markdown
        content: "[Zwavejs webpage](http://192.168.1.226:8091) with devices."
  - title: Thermostat
    cards:
      # https://www.home-assistant.io/lovelace/thermostat/
      - type: thermostat
        entity: climate.t6_pro_z_wave_programmable_thermostat_thermostat_mode
        name: Thermostat
      - type: history-graph
        title: Temperature
        entities:
          - entity: sensor.t6_pro_z_wave_programmable_thermostat_air_temperature
            name: Temperature
      - type: history-graph
        title: Humidity
        entities:
          - entity: sensor.t6_pro_z_wave_programmable_thermostat_humidity
            name: Humidity
  - title: Cameras/Motion
    cards:
      # https://www.home-assistant.io/lovelace/picture-glance/
      - type: picture-glance
        camera_image: camera.inside
        title: Inside Camera
        entities:
          - entity: sensor.inside_person
            show_state: true
      - type: picture-glance
        camera_image: camera.frontdoor
        title: Frontdoor Camera
        entities:
          - entity: sensor.frontdoor_person
            show_state: true
      - type: picture-glance
        camera_image: camera.backdoor
        title: Backdoor Camera
        entities:
          - entity: sensor.backdoor_person
            show_state: true
      # https://www.home-assistant.io/lovelace/entities/
      - type: entities
        title: Cameras
        show_header_toggle: false
        entities:
          - entity: switch.amcrestcamera_state
            name: Camera
            icon: mdi:video
      - type: history-graph
        title: Camera Status
        entities:
          - camera.inside
          - camera.frontdoor
          - camera.backdoor
      - type: history-graph
        title: Person Detected
        entities:
          - entity: binary_sensor.inside_person_motion
            name: Person Inside
          - entity: binary_sensor.frontdoor_person_motion
            name: Person Frontdoor
          - entity: binary_sensor.backdoor_person_motion
            name: Person Backdoor
      - type: markdown
        content: "[Frigate webpage](http://192.168.1.113:5000) showing detection events."
      - type: history-graph
        title: Motion Sensor
        entities:
          - binary_sensor.lumi_lumi_sensor_motion_aq2_a2fe8704_ias_zone
  - title: Weather
    cards:
      - type: weather-forecast
        entity: weather.home
      - type: picture-glance
        title: Animated Radar
        camera_image: camera.animated_radar
        entities:
          - camera.animated_radar
  - title: System Monitor
    cards:
      - type: history-graph
        title: CPU Load
        entities:
          - sensor.load_5m
      - type: history-graph
        title: Memory
        entities:
          - sensor.memory_use_percent
          - sensor.swap_use_percent
      - type: history-graph
        title: CPU Temp
        entities:
          - sensor.cpu_temperature
      - type: gauge
        name: / Disk Use
        unit: '%'
        entity: sensor.disk_use_percent
        severity:
          green: 0
          yellow: 60
          red: 85
      - type: gauge
        name: Memory Use
        unit: '%'
        entity: sensor.memory_use_percent
        severity:
          green: 0
          yellow: 60
          red: 85
      - type: gauge
        name: Swap Use
        unit: '%'
        entity: sensor.swap_use_percent
        severity:
          green: 0
          yellow: 60
          red: 85
      - type: markdown
        content: "Home Assistant Uptime: {{ states('sensor.uptime_days') }}"
      - type: gauge
        name: Frigate Used Diskspace
        unit: '%'
        entity: sensor.frigate_used_space_percentage
        severity:
          green: 0
          yellow: 70
          red: 85
  - title: Updates
    cards:
      # https://www.home-assistant.io/integrations/updater/
      # https://www.home-assistant.io/lovelace/glance/
      - type: glance
        title: Updates
        entities:
          - entity: binary_sensor.updater
            name: Home Assistant
          - entity: binary_sensor.frigate_update
            name: Frigate
      - type: markdown
        content: "Home Assistant [{{ state_attr('binary_sensor.updater', 'newest_version') }}](https://github.com/home-assistant/core/releases) is available.  You're running version {{ states('sensor.current_version') }}."
      - type: markdown
        content: "Frigate release [{{ state_attr('sensor.frigate_latest_release', 'tag_name') }}](https://github.com/blakeblackshear/frigate/releases) is available.  You're running version: {{ states('sensor.frigate_version') }}"
  - title: Batteries
    cards:
      - type: history-graph
        title: Thermostat Battery
        entities:
          - entity: sensor.nodeid_3_battery_level
            name: Thermostat Battery
      - type: history-graph
        title: Aqara Motion Sensor Battery
        entities:
          - entity: sensor.lumi_lumi_sensor_motion_aq2_a2fe8704_power
            name: Aqara Motion Sensor Battery