title: Home
views:
  - title: Controls
    cards:
      # https://www.home-assistant.io/lovelace/entities/
      - type: entities
        title: Toggle Lights
        show_header_toggle: false
        entities:
          - entity: switch.piano_lamp
            icon: mdi:lamp
          - entity: switch.living_room_lamp
            icon: mdi:floor-lamp
          - entity: switch.bedroom_lamp
            icon: mdi:lamp
      # https://www.home-assistant.io/lovelace/entities/
      - type: entities
        title: Toggle Alarm
        show_header_toggle: false
        entities:
          - entity: input_boolean.alarm
            name: Alarm
            icon: mdi:alarm-light
  - title: Cameras
    cards:
      # https://www.home-assistant.io/lovelace/picture-glance/
      - type: picture-glance
        camera_image: camera.frontcamera
        title: Front Camera
        entities:
          - entity: sensor.frontcamera_events
            show_state: true
      - type: picture-glance
        camera_image: camera.insidecamera
        title: Inside Camera
        entities:
          - entity: sensor.insidecamera_events
            show_state: true
      # https://www.home-assistant.io/lovelace/entities/
      - type: entities
        title: Toggle Cameras
        show_header_toggle: false
        entities:
          - entity: switch.frontcamera_state
            name: Front Camera
            icon: mdi:video
          - entity: switch.insidecamera_state
            name: Inside Camera
            icon: mdi:video
      - type: history-graph
        title: 'Camera Status'
        entities:
          - camera.frontcamera
          - camera.insidecamera
      - type: markdown
        content: "Zoneminder release {{ state_attr('sensor.zoneminder_latest_release', 'tag_name') }} is available.  You're running version: {{ state_attr('sensor.zoneminder_version', 'version') }}"
  - title: Weather
    cards:
      - type: picture-glance
        title: Animated Radar
        camera_image: camera.animated_radar
        entities:
          - camera.animated_radar
  - title: System Monitor
    cards:
      - type: history-graph
        title: 'CPU Load'
        entities:
          - sensor.load_5m
      - type: history-graph
        title: 'Memory'
        entities:
          - sensor.memory_use_percent
          - sensor.swap_use_percent
      - type: history-graph
        title: 'CPU Temp'
        entities:
          - sensor.cpu_temperature
      - type: gauge
        name: / Disk Use
        unit: '%'
        entity: sensor.disk_use_percent
        severity:
          green: 0
          yellow: 60
          red: 85
      - type: gauge
        name: Memory Use
        unit: '%'
        entity: sensor.memory_use_percent
        severity:
          green: 0
          yellow: 60
          red: 85
      - type: gauge
        name: Swap Use
        unit: '%'
        entity: sensor.swap_use_percent
        severity:
          green: 0
          yellow: 60
          red: 85
      - type: markdown
        content: "Home Assistant Uptime: {{ states('sensor.uptime') }} days."
  - title: Updater
    cards:
      # https://www.home-assistant.io/integrations/updater/
      # https://www.home-assistant.io/lovelace/glance/
      - type: glance
        title: Update Available?
        entities:
          - binary_sensor.updater
      - type: markdown
        content: "Home Assistant {{ state_attr('binary_sensor.updater', 'newest_version') }} is available.  You're running version {{ states('sensor.current_version') }}."